In [1]:
from brown_edu_dmtools.dmtools_client_package.dmtools_client_module import DMToolsClient

In [2]:
## get api key and user id from local .env file
from dotenv import load_dotenv
import os
from os import environ, path
#BASE_DIR = path.abspath(path.dirname(__file__))
BASE_DIR = os.getcwd()
load_dotenv(path.join(BASE_DIR, ".env"))
MY_DMTOOLS_APIKEY = environ.get("MY_DMTOOLS_APIKEY")
MY_DMTOOLS_USERID = environ.get("MY_DMTOOLS_USERID")
Client = DMToolsClient(MY_DMTOOLS_USERID, MY_DMTOOLS_APIKEY)

In [3]:
import json

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('list_columns.csv')
df.head(5)
df[df['subject']=='data']

       purpose subject                   key  value
0   list_table    data           archived_at      0
1   list_table    data            created_at      0
2   list_table    data            creator_id      0
3   list_table    data                  data      0
4   list_table    data          data_comment      0
5   list_table    data            data_label      1
6   list_table    data        data_reference      1
7   list_table    data           data_values      0
8   list_table    data  date_of_announcement      0
9   list_table    data       date_of_run_end      0
10  list_table    data     date_of_run_start      0
11  list_table    data         date_official      0
12  list_table    data         default_color      0
13  list_table    data         default_style      0
14  list_table    data            experiment      1
15  list_table    data             file_name      0
16  list_table    data          greatest_hit      1
17  list_table    data                    id      1
18  list_table    data              limit_id      0
19  list_table    data      measurement_type      1
20  list_table    data               nomhash      0
21  list_table    data              official      1
22  list_table    data                  open      1
23  list_table    data                public      1
24  list_table    data                rating      1
25  list_table    data           result_type      1
26  list_table    data       spin_dependency      1
27  list_table    data               subject      0
28  list_table    data            updated_at      1
29  list_table    data             x_rescale      0
30  list_table    data               x_units      0
31  list_table    data             y_rescale      0
32  list_table    data               y_units      0
33  list_table    data                  year      1

In [6]:
for index, row in df.iterrows():
    purpose = row['purpose']
    subject = row['subject']
    key = row['key']
    value = row['value']
    data = { 'key_purpose' : purpose,
            'key_subject' : subject,
            'key' : key,
            'value' : str(value),
            'value_datatype' : 'integer'}
    print(data)
    r = Client.create(subject='graph', data=data)
            
'''
#r = Client.read(subject='graph')
#r
'''

{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'creator_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'data', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'data_comment', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'data_label', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'data_reference', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'data_values', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'date_of_announcement', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'date_of_run_end', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'date_of_run_start', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'date_official', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'default_color', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'default_style', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'experiment', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'file_name', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'greatest_hit', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'limit_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'measurement_type', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'nomhash', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'official', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'open', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'public', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'rating', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'result_type', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'spin_dependency', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'x_rescale', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'x_units', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'y_rescale', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'y_units', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data', 'key': 'year', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'color', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'data_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'limit_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'name', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'old_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'old_plot_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'open', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'plot_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'style', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'data_display', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'dropdown_display', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'dropdown_subject', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'dropdown_value', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'name', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'old_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'open', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'dropdown', 'key': 'updated_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'key', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'open', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'parent_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'value', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'graph', 'key': 'value_datatype', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'color', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'plot_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'style', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'limit_display', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'class_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'class_name', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'ownership', 'key': 'user_id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'archived_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'created_at', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'id', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'legend_eps', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'legend_png', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'name', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'no_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'old_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'old_name', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'old_user_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'open', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'plot_eps', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'plot_png', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'subject', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'updated_at', 'value': '1', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'user_id', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'x_max', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'x_min', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'x_units', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'y_max', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'y_min', 'value': '0', 'value_datatype': 'integer'}
{'key_purpose': 'list_table', 'key_subject': 'plot', 'key': 'y_units', 'value': '0', 'value_datatype': 'integer'}

"\n#r = Client.read(subject='graph')\n#r\n"

In [6]:
new_graph = {'parent_id': -1,
  'open': 0,
  'value': 'experiment',
  'created_at': '2024-08-27T15:27:27',
  'archived_at': '1980-01-01T00:00:00',
  'key': 'experiment',
  'subject': 'graph',
  'value_datatype': 'text',
  'updated_at': '2024-08-27T15:27:27'}

In [7]:
# r = Client.create(subject='graph',data=new_graph)

In [8]:
r = Client.read(subject='graph',id=127)
r

[{'id': 127,
  'open': 1,
  'parent_id': -1,
  'subject': 'graph',
  'key_subject': 'data',
  'key_purpose': 'list_table',
  'key': 'limit_id',
  'value': '0',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:13'}]

In [13]:
# Define the query parameters as a dictionary
params = {
    'value': '1',
    'key_subject': 'data',
    'key_purpose': 'list_table'
}

params_as_string = json.dumps(params)

# Pass the encoded query to the API client
r = Client.query(subject='graph', query_criteria=params_as_string)

query function encoded query string >>>  value%3D1%26key_subject%3Ddata%26key_purpose%3Dlist_table
query_url >>>>>>>>>>> https://dmtools.brown.edu/dmtool/fastapi_data/open/data/0.0/graph/query/?query_in=value%3D1%26key_subject%3Ddata%26key_purpose%3Dlist_table

In [15]:
#r

In [16]:
new_df = pd.DataFrame(data=r)
table_columns = new_df['key'].tolist()
table_columns

['id',
 'experiment',
 'spin_dependency',
 'result_type',
 'measurement_type',
 'year']

In [19]:
r

[{'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:08',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'graph',
  'id': 114,
  'parent_id': -1,
  'key': 'subject',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:08'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:09',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'graph',
  'id': 115,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:09'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:09',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'graph',
  'id': 116,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:09'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:09',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'graph',
  'id': 117,
  'parent_id': -1,
  'key': 'archived_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:09'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:10',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 118,
  'parent_id': -1,
  'key': 'old_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:10'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:10',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 119,
  'parent_id': -1,
  'key': 'subject',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:10'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:11',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 120,
  'parent_id': -1,
  'key': 'name',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:11'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:11',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 121,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:11'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:11',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 122,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:11'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:12',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'dropdown',
  'id': 123,
  'parent_id': -1,
  'key': 'archived_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:12'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:12',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'limit_display',
  'id': 124,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:12'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:13',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'limit_display',
  'id': 125,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:13'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:13',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 126,
  'parent_id': -1,
  'key': 'subject',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:13'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:13',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 127,
  'parent_id': -1,
  'key': 'limit_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:13'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:14',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 128,
  'parent_id': -1,
  'key': 'nomhash',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:14'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:14',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 129,
  'parent_id': -1,
  'key': 'x_units',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:14'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:15',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 130,
  'parent_id': -1,
  'key': 'y_units',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:15'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:15',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 131,
  'parent_id': -1,
  'key': 'x_rescale',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:15'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:15',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 132,
  'parent_id': -1,
  'key': 'y_rescale',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:15'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:16',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 133,
  'parent_id': -1,
  'key': 'default_color',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:16'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:16',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 134,
  'parent_id': -1,
  'key': 'default_style',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:16'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:17',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 135,
  'parent_id': -1,
  'key': 'data_values',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:17'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:17',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 136,
  'parent_id': -1,
  'key': 'data',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:17'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:17',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 137,
  'parent_id': -1,
  'key': 'data_label',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:17'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:18',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 138,
  'parent_id': -1,
  'key': 'data_comment',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:18'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:18',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 139,
  'parent_id': -1,
  'key': 'data_reference',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:18'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:19',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 140,
  'parent_id': -1,
  'key': 'file_name',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:19'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:19',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 141,
  'parent_id': -1,
  'key': 'creator_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:19'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:19',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 142,
  'parent_id': -1,
  'key': 'date_of_run_start',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:19'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:20',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 143,
  'parent_id': -1,
  'key': 'date_of_run_end',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:20'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:20',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 144,
  'parent_id': -1,
  'key': 'date_of_announcement',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:20'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:21',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 145,
  'parent_id': -1,
  'key': 'date_official',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:21'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:21',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 146,
  'parent_id': -1,
  'key': 'rating',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:21'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:21',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 147,
  'parent_id': -1,
  'key': 'public',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:21'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:22',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 148,
  'parent_id': -1,
  'key': 'open',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:22'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:22',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 149,
  'parent_id': -1,
  'key': 'official',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:22'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:23',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 150,
  'parent_id': -1,
  'key': 'greatest_hit',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:23'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:23',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 151,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:23'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:23',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 152,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:23'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:24',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data',
  'id': 153,
  'parent_id': -1,
  'key': 'archived_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:24'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:24',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 154,
  'parent_id': -1,
  'key': 'subject',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:24'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:25',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 155,
  'parent_id': -1,
  'key': 'old_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:25'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:25',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 156,
  'parent_id': -1,
  'key': 'old_plot_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:25'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:25',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 157,
  'parent_id': -1,
  'key': 'limit_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:25'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:26',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 158,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:26'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:26',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 159,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:26'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:27',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 160,
  'parent_id': -1,
  'key': 'archived_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:27'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:27',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'data_display',
  'id': 161,
  'parent_id': -1,
  'key': 'open',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:27'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:27',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 162,
  'parent_id': -1,
  'key': 'subject',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:27'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:28',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 163,
  'parent_id': -1,
  'key': 'old_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:28'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:28',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 164,
  'parent_id': -1,
  'key': 'old_name',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:28'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:29',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 165,
  'parent_id': -1,
  'key': 'old_user_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:29'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:29',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 166,
  'parent_id': -1,
  'key': 'x_min',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:29'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:29',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 167,
  'parent_id': -1,
  'key': 'x_max',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:29'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:30',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 168,
  'parent_id': -1,
  'key': 'y_min',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:30'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:30',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 169,
  'parent_id': -1,
  'key': 'y_max',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:30'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:31',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 170,
  'parent_id': -1,
  'key': 'x_units',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:31'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:31',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 171,
  'parent_id': -1,
  'key': 'y_units',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:31'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:31',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 172,
  'parent_id': -1,
  'key': 'user_id',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:31'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:32',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 173,
  'parent_id': -1,
  'key': 'created_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:32'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:32',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 174,
  'parent_id': -1,
  'key': 'updated_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:32'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:33',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 175,
  'parent_id': -1,
  'key': 'archived_at',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:33'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:33',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 176,
  'parent_id': -1,
  'key': 'plot_png',
  'value_datatype': 'integer',
  'updated_at': '2024-08-28T14:57:33'},
 {'open': 1,
  'key_purpose': 'list_table',
  'value': '0',
  'created_at': '2024-08-28T14:57:33',
  'archived_at': '1980-01-01T00:00:00',
  'subject': 'graph',
  'key_subject': 'plot',
  'id': 177,
  'parent_id': -1,
  'key': 'legend_png',
  'value_datatype': 'integer',